<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="INFO-LTP-014" name="forgot_runner_PO" tests="1" failures="1" timestamp="14 Jul 2019 05:25:14 GMT" time="70.546" errors="0">
  <testcase name="feature" time="70.18" classname="com.cucumber.framework.runner.Infotech_HR.forgot_runner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: forgot_step is fail expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: forgot_step is fail expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
Caused by: java.lang.AssertionError: forgot_step is fail expected [true] but found [false]
	at com.cucumber.framework.stepdefinition.InfoTech_cloud.forgot_step.verify_the_succcess_alert_message_is_displayed(forgot_step.java:51)
	at âœ½.Then Verify the succcess alert message is displayed(featurefile/Infofeature/forgot_po.feature:10)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- forgot_runner_PO -->
